// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:SheltonHTPC.NavigationContent.LayoutSections.SettingsSectionModel.Initialize(System.String)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:SheltonHTPC.Utils.DataTools.PurgeData(SheltonHTPC.Data.Entities.GeneralSettings)~System.Threading.Tasks.Task")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:SheltonHTPC.MainWindowViewModel.ChangeContentTo(SheltonHTPC.NavigationContent.ContentKind)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:SheltonHTPC.NavigationContent.GeneralSettingsSections.ToolsSectionModel.DoPurge(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:SheltonHTPC.NavigationContent.LayoutSections.BackgroundSetsSectionModel.DeleteBackgroundSet(System.Windows.DependencyObject,SheltonHTPC.NavigationContent.LayoutSections.EditableBackgroundSet)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:SheltonHTPC.Utils.OngoingTaskManager.CreateAndStartOngoingTask(System.String,SheltonHTPC.Utils.OngoingTaskModel.ProgressDisplayKind,System.Action{SheltonHTPC.Utils.OngoingTaskModel},System.Int32)~SheltonHTPC.Utils.OngoingTaskModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:SheltonHTPC.Utils.OngoingTaskModel.#ctor(System.Action{SheltonHTPC.Utils.OngoingTaskModel})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:SheltonHTPC.Utils.OngoingTaskModel.Start")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2008:Do not create tasks without passing a TaskScheduler", Justification = "<Pending>", Scope = "member", Target = "~M:SheltonHTPC.NavigationContent.NavigationContentModelBase`1.OnNavigatedAwayFrom~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:SheltonHTPC.NavigationContent.LayoutSections.EditableBackgroundSetImage.CommitImagesToFileStorage(SheltonHTPC.NavigationContent.LayoutSections.EditableBackgroundSet)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2008:Do not create tasks without passing a TaskScheduler", Justification = "<Pending>", Scope = "member", Target = "~P:SheltonHTPC.NavigationContent.LayoutSections.EditableBackgroundSetImage.ThumbnailImage")]
